#!/usr/bin/env python3
"""Assemble docs/llm/first_system_prompt.md from bundled LLM context files."""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from urirun_llm_runtime.llm_context import build_first_system_prompt, docs_index


def main() -> int:
    out = ROOT / "docs" / "llm" / "first_system_prompt.md"
    header = (
        "<!-- AUTO-GENERATED by scripts/assemble_llm_prompt.py — do not edit by hand -->\n\n"
        "# URI Runtime — First System Prompt for LLM\n\n"
        "Fetch index:\n"
    )
    for key, url in docs_index().items():
        header += f"- {key}: {url}\n"
    header += "\n---\n\n"
    body = build_first_system_prompt()
    out.write_text(header + body + "\n", encoding="utf-8")
    print(f"wrote {out} ({len(header + body)} chars)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
